// <auto-generated />
using System;
using CellPhoneShop.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CellPhoneShop.DataAccess.Migrations
{
    [DbContext(typeof(CellPhoneShopContext))]
    partial class CellPhoneShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BrandID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.HasKey("BrandId")
                        .HasName("PK__Brand__DAD4F3BEFBB42C55");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Brand", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CartID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CartId")
                        .HasName("PK__Cart__51BCD79752FC7337");

                    b.HasIndex("UserId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CartItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("CartID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("VariantID");

                    b.HasKey("CartItemId")
                        .HasName("PK__CartItem__488B0B2ACBA0D688");

                    b.HasIndex("CartId");

                    b.HasIndex("VariantId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ColorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"));

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("PhoneId")
                        .HasColumnType("int")
                        .HasColumnName("PhoneID");

                    b.HasKey("ColorId")
                        .HasName("PK__Colors__8DA7676D021378B1");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("PhoneId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.ColorImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int?>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("ColorID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.HasKey("ImageId")
                        .HasName("PK__ColorIma__7516F4EC9D9A2882");

                    b.HasIndex("ColorId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("ColorImages");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CommentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("PhoneId")
                        .HasColumnType("int")
                        .HasColumnName("PhoneID");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CommentId")
                        .HasName("PK__Comment__C3B4DFAAB173E4F3");

                    b.HasIndex("PhoneId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("DistrictId")
                        .HasName("PK__District__85FDA4C6FF5DADDC");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Master", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MasterDataId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__Master__3214EC07F8ECE0A2");

                    b.ToTable("Master", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NewsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("AuthorID");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NewsId")
                        .HasName("PK__News__954EBDD39F8B436E");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("News");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("AddressDetail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("WardId")
                        .HasColumnType("int");

                    b.HasKey("OrderId")
                        .HasName("PK__Order__C3905BAF99A18C87");

                    b.HasIndex("UserId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("VariantID");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__D3B9D30CCD69F7A1");

                    b.HasIndex("OrderId");

                    b.HasIndex("VariantId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Phone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhoneID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhoneId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("BrandID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("PhoneName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PhoneId")
                        .HasName("PK__Phone__F3EE4BD027224A8E");

                    b.HasIndex("BrandId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Phone", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.PhoneAttribute", b =>
                {
                    b.Property<int>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttributeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AttributeId")
                        .HasName("PK__PhoneAtt__C218054B7F60ED59");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("PhoneAttribute", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.PhoneAttributeMapping", b =>
                {
                    b.Property<int>("PhoneId")
                        .HasColumnType("int")
                        .HasColumnName("PhoneID");

                    b.Property<int>("AttributeId")
                        .HasColumnType("int")
                        .HasColumnName("AttributeID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("PhoneId", "AttributeId")
                        .HasName("PK__PhoneAtt__NEW4");

                    b.HasIndex("AttributeId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("PhoneAttributeMapping", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.PhonePromotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("PromotionID");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("VariantID");

                    b.HasKey("Id")
                        .HasName("PK__PhonePro__3214EC275DC19495");

                    b.HasIndex("PromotionId");

                    b.HasIndex("VariantId");

                    b.ToTable("PhonePromotion", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.PhoneVariant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VariantID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariantId"));

                    b.Property<int?>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("ColorID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("PhoneId")
                        .HasColumnType("int")
                        .HasColumnName("PhoneID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("VariantId")
                        .HasName("PK__PhoneVar__0EA233E4FF148454");

                    b.HasIndex("ColorId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("PhoneId");

                    b.ToTable("PhoneVariant", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PromotionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PromotionId")
                        .HasName("PK__Promotio__52C42F2F7EE87D58");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProvinceId")
                        .HasName("PK__Province__FD0A6F83240EA978");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.UserAccount", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AddressDetail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("WardId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__UserAcco__1788CCACCFD2B959");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex(new[] { "Email" }, "UQ__UserAcco__A9D1053452242E96")
                        .IsUnique();

                    b.ToTable("UserAccount", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.VariantAttribute", b =>
                {
                    b.Property<int>("VariantAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VariantAttributeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariantAttributeId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VariantAttributeId")
                        .HasName("PK__VariantA__NEW10");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("VariantAttribute", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.VariantAttributeMapping", b =>
                {
                    b.Property<int>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("VariantID");

                    b.Property<int>("ValueId")
                        .HasColumnType("int")
                        .HasColumnName("ValueID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.HasKey("VariantId", "ValueId")
                        .HasName("PK__VariantA__NEW19");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("ValueId");

                    b.ToTable("VariantAttributeMapping", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.VariantAttributeValue", b =>
                {
                    b.Property<int>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ValueID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValueId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("VariantAttributeId")
                        .HasColumnType("int")
                        .HasColumnName("VariantAttributeID");

                    b.HasKey("ValueId")
                        .HasName("PK__VariantA__NEW14");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("VariantAttributeId");

                    b.ToTable("VariantAttributeValue", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Ward", b =>
                {
                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WardId")
                        .HasName("PK__Wards__C6BD9BCAA45268A1");

                    b.HasIndex("DistrictId");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Warranty", b =>
                {
                    b.Property<int>("WarrantyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WarrantyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarrantyId"));

                    b.Property<string>("Contact")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("VariantID");

                    b.Property<string>("WarrantyCenter")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("WarrantyPeriod")
                        .HasColumnType("int");

                    b.HasKey("WarrantyId")
                        .HasName("PK__Warranty__2ED318F3C9728E3D");

                    b.HasIndex("VariantId");

                    b.ToTable("Warranty", (string)null);
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Brand", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "CreatedByNavigation")
                        .WithMany("BrandCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Brand__CreatedBy__6FE99F9F");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "DeletedByNavigation")
                        .WithMany("BrandDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__Brand__DeletedBy__70DDC3D8");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "ModifiedByNavigation")
                        .WithMany("BrandModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Brand__ModifiedB__71D1E811");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Cart", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Cart__UserID__72C60C4A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.CartItem", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .HasConstraintName("FK__CartItem__CartID__73BA3083");

                    b.HasOne("CellPhoneShop.Domain.Models.PhoneVariant", "Variant")
                        .WithMany("CartItems")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("FK__CartItem__Varian__74AE54BC");

                    b.Navigation("Cart");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Color", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "CreatedByNavigation")
                        .WithMany("ColorCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Colors__CreatedB__797309D9");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "DeletedByNavigation")
                        .WithMany("ColorDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__Colors__DeletedB__7A672E12");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "ModifiedByNavigation")
                        .WithMany("ColorModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Colors__Modified__7B5B524B");

                    b.HasOne("CellPhoneShop.Domain.Models.Phone", "Phone")
                        .WithMany("Colors")
                        .HasForeignKey("PhoneId")
                        .HasConstraintName("FK__Colors__PhoneID__7C4F7684");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.ColorImage", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.Color", "Color")
                        .WithMany("ColorImages")
                        .HasForeignKey("ColorId")
                        .HasConstraintName("FK__ColorImag__Color__75A278F5");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "CreatedByNavigation")
                        .WithMany("ColorImageCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__ColorImag__Creat__76969D2E");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "DeletedByNavigation")
                        .WithMany("ColorImageDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__ColorImag__Delet__778AC167");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "ModifiedByNavigation")
                        .WithMany("ColorImageModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__ColorImag__Modif__787EE5A0");

                    b.Navigation("Color");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Comment", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.Phone", "Phone")
                        .WithMany("Comments")
                        .HasForeignKey("PhoneId")
                        .HasConstraintName("FK__Comment__PhoneID__7D439ABD");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Comment__UserID__7E37BEF6");

                    b.Navigation("Phone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.District", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .HasConstraintName("FK__Districts__Provi__7F2BE32F");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.News", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "Author")
                        .WithMany("NewsAuthors")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("FK__News__AuthorID__00200768");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "CreatedByNavigation")
                        .WithMany("NewsCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__News__CreatedBy__01142BA1");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "DeletedByNavigation")
                        .WithMany("NewsDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__News__DeletedBy__02084FDA");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "ModifiedByNavigation")
                        .WithMany("NewsModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__News__ModifiedBy__02FC7413");

                    b.Navigation("Author");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Order", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Order__UserID__03F0984C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.OrderDetail", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__OrderDeta__Order__04E4BC85");

                    b.HasOne("CellPhoneShop.Domain.Models.PhoneVariant", "Variant")
                        .WithMany("OrderDetails")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("FK__OrderDeta__Varia__05D8E0BE");

                    b.Navigation("Order");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Phone", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.Brand", "Brand")
                        .WithMany("Phones")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK__Phone__BrandID__06CD04F7");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "CreatedByNavigation")
                        .WithMany("PhoneCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Phone__CreatedBy__07C12930");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "DeletedByNavigation")
                        .WithMany("PhoneDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__Phone__DeletedBy__08B54D69");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "ModifiedByNavigation")
                        .WithMany("PhoneModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Phone__ModifiedB__09A971A2");

                    b.Navigation("Brand");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.PhoneAttribute", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "CreatedByNavigation")
                        .WithMany("PhoneAttributeCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__PhoneAttr__Creat__NEW1");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "DeletedByNavigation")
                        .WithMany("PhoneAttributeDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__PhoneAttr__Delet__NEW3");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "ModifiedByNavigation")
                        .WithMany("PhoneAttributeModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__PhoneAttr__Modif__NEW2");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.PhoneAttributeMapping", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.PhoneAttribute", "Attribute")
                        .WithMany("PhoneAttributeMappings")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PhoneAttr__Attri__NEW6");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "CreatedByNavigation")
                        .WithMany("PhoneAttributeMappingCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__PhoneAttr__Creat__NEW7");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "DeletedByNavigation")
                        .WithMany("PhoneAttributeMappingDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__PhoneAttr__Delet__NEW9");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "ModifiedByNavigation")
                        .WithMany("PhoneAttributeMappingModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__PhoneAttr__Modif__NEW8");

                    b.HasOne("CellPhoneShop.Domain.Models.Phone", "Phone")
                        .WithMany("PhoneAttributeMappings")
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PhoneAttr__Phone__NEW5");

                    b.Navigation("Attribute");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.PhonePromotion", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.Promotion", "Promotion")
                        .WithMany("PhonePromotions")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK__PhoneProm__Promo__0A9D95DB");

                    b.HasOne("CellPhoneShop.Domain.Models.PhoneVariant", "Variant")
                        .WithMany("PhonePromotions")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("FK__PhoneProm__Varia__0B91BA14");

                    b.Navigation("Promotion");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.PhoneVariant", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.Color", "Color")
                        .WithMany("PhoneVariants")
                        .HasForeignKey("ColorId")
                        .HasConstraintName("FK__PhoneVari__Color__NEW26");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "CreatedByNavigation")
                        .WithMany("PhoneVariantCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__PhoneVari__Creat__NEW27");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "DeletedByNavigation")
                        .WithMany("PhoneVariantDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__PhoneVari__Delet__NEW29");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "ModifiedByNavigation")
                        .WithMany("PhoneVariantModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__PhoneVari__Modif__NEW28");

                    b.HasOne("CellPhoneShop.Domain.Models.Phone", "Phone")
                        .WithMany("PhoneVariants")
                        .HasForeignKey("PhoneId")
                        .HasConstraintName("FK__PhoneVari__Phone__NEW25");

                    b.Navigation("Color");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Promotion", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "CreatedByNavigation")
                        .WithMany("PromotionCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Promotion__Creat__114A936A");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "DeletedByNavigation")
                        .WithMany("PromotionDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__Promotion__Delet__123EB7A3");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "ModifiedByNavigation")
                        .WithMany("PromotionModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Promotion__Modif__1332DBDC");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.UserAccount", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "CreatedByNavigation")
                        .WithMany("InverseCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__UserAccou__Creat__14270015");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "DeletedByNavigation")
                        .WithMany("InverseDeletedByNavigation")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__UserAccou__Delet__151B244E");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "ModifiedByNavigation")
                        .WithMany("InverseModifiedByNavigation")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__UserAccou__Modif__160F4887");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.VariantAttribute", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "CreatedByNavigation")
                        .WithMany("VariantAttributeCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__VariantAt__Creat__NEW11");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "DeletedByNavigation")
                        .WithMany("VariantAttributeDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__VariantAt__Delet__NEW13");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "ModifiedByNavigation")
                        .WithMany("VariantAttributeModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__VariantAt__Modif__NEW12");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.VariantAttributeMapping", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "CreatedByNavigation")
                        .WithMany("VariantAttributeMappingCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__VariantAt__Creat__NEW22");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "DeletedByNavigation")
                        .WithMany("VariantAttributeMappingDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__VariantAt__Delet__NEW24");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "ModifiedByNavigation")
                        .WithMany("VariantAttributeMappingModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__VariantAt__Modif__NEW23");

                    b.HasOne("CellPhoneShop.Domain.Models.VariantAttributeValue", "AttributeValue")
                        .WithMany("VariantAttributeMappings")
                        .HasForeignKey("ValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__VariantAt__Value__NEW21");

                    b.HasOne("CellPhoneShop.Domain.Models.PhoneVariant", "PhoneVariant")
                        .WithMany("VariantAttributeMappings")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__VariantAt__Varia__NEW20");

                    b.Navigation("AttributeValue");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("PhoneVariant");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.VariantAttributeValue", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "CreatedByNavigation")
                        .WithMany("VariantAttributeValueCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__VariantAt__Creat__NEW16");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "DeletedByNavigation")
                        .WithMany("VariantAttributeValueDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK__VariantAt__Delet__NEW18");

                    b.HasOne("CellPhoneShop.Domain.Models.UserAccount", "ModifiedByNavigation")
                        .WithMany("VariantAttributeValueModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__VariantAt__Modif__NEW17");

                    b.HasOne("CellPhoneShop.Domain.Models.VariantAttribute", "VariantAttribute")
                        .WithMany("VariantAttributeValues")
                        .HasForeignKey("VariantAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__VariantAt__Varia__NEW15");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("VariantAttribute");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Ward", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.District", "District")
                        .WithMany("Wards")
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("FK__Wards__DistrictI__17036CC0");

                    b.Navigation("District");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Warranty", b =>
                {
                    b.HasOne("CellPhoneShop.Domain.Models.PhoneVariant", "Variant")
                        .WithMany("Warranties")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("FK__Warranty__Varian__17F790F9");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Brand", b =>
                {
                    b.Navigation("Phones");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Color", b =>
                {
                    b.Navigation("ColorImages");

                    b.Navigation("PhoneVariants");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.District", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Phone", b =>
                {
                    b.Navigation("Colors");

                    b.Navigation("Comments");

                    b.Navigation("PhoneAttributeMappings");

                    b.Navigation("PhoneVariants");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.PhoneAttribute", b =>
                {
                    b.Navigation("PhoneAttributeMappings");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.PhoneVariant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("PhonePromotions");

                    b.Navigation("VariantAttributeMappings");

                    b.Navigation("Warranties");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Promotion", b =>
                {
                    b.Navigation("PhonePromotions");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.UserAccount", b =>
                {
                    b.Navigation("BrandCreatedByNavigations");

                    b.Navigation("BrandDeletedByNavigations");

                    b.Navigation("BrandModifiedByNavigations");

                    b.Navigation("Carts");

                    b.Navigation("ColorCreatedByNavigations");

                    b.Navigation("ColorDeletedByNavigations");

                    b.Navigation("ColorImageCreatedByNavigations");

                    b.Navigation("ColorImageDeletedByNavigations");

                    b.Navigation("ColorImageModifiedByNavigations");

                    b.Navigation("ColorModifiedByNavigations");

                    b.Navigation("Comments");

                    b.Navigation("InverseCreatedByNavigation");

                    b.Navigation("InverseDeletedByNavigation");

                    b.Navigation("InverseModifiedByNavigation");

                    b.Navigation("NewsAuthors");

                    b.Navigation("NewsCreatedByNavigations");

                    b.Navigation("NewsDeletedByNavigations");

                    b.Navigation("NewsModifiedByNavigations");

                    b.Navigation("Orders");

                    b.Navigation("PhoneAttributeCreatedByNavigations");

                    b.Navigation("PhoneAttributeDeletedByNavigations");

                    b.Navigation("PhoneAttributeMappingCreatedByNavigations");

                    b.Navigation("PhoneAttributeMappingDeletedByNavigations");

                    b.Navigation("PhoneAttributeMappingModifiedByNavigations");

                    b.Navigation("PhoneAttributeModifiedByNavigations");

                    b.Navigation("PhoneCreatedByNavigations");

                    b.Navigation("PhoneDeletedByNavigations");

                    b.Navigation("PhoneModifiedByNavigations");

                    b.Navigation("PhoneVariantCreatedByNavigations");

                    b.Navigation("PhoneVariantDeletedByNavigations");

                    b.Navigation("PhoneVariantModifiedByNavigations");

                    b.Navigation("PromotionCreatedByNavigations");

                    b.Navigation("PromotionDeletedByNavigations");

                    b.Navigation("PromotionModifiedByNavigations");

                    b.Navigation("VariantAttributeCreatedByNavigations");

                    b.Navigation("VariantAttributeDeletedByNavigations");

                    b.Navigation("VariantAttributeMappingCreatedByNavigations");

                    b.Navigation("VariantAttributeMappingDeletedByNavigations");

                    b.Navigation("VariantAttributeMappingModifiedByNavigations");

                    b.Navigation("VariantAttributeModifiedByNavigations");

                    b.Navigation("VariantAttributeValueCreatedByNavigations");

                    b.Navigation("VariantAttributeValueDeletedByNavigations");

                    b.Navigation("VariantAttributeValueModifiedByNavigations");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.VariantAttribute", b =>
                {
                    b.Navigation("VariantAttributeValues");
                });

            modelBuilder.Entity("CellPhoneShop.Domain.Models.VariantAttributeValue", b =>
                {
                    b.Navigation("VariantAttributeMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
